################################################################################
#
# libsndfile with lame and mpg123
#
################################################################################

LIBSNDFILE_WITH_LAME_AND_MPG123_VERSION = $(LIBSNDFILE_VERSION)
LIBSNDFILE_WITH_LAME_AND_MPG123_SOURCE = $(LIBSNDFILE_SOURCE)
LIBSNDFILE_WITH_LAME_AND_MPG123_SITE = $(LIBSNDFILE_SITE)
LIBSNDFILE_WITH_LAME_AND_MPG123_INSTALL_STAGING = $(LIBSNDFILE_INSTALL_STAGING)
LIBSNDFILE_WITH_LAME_AND_MPG123_LICENSE = $(LIBSNDFILE_LICENSE)
LIBSNDFILE_WITH_LAME_AND_MPG123_LICENSE_FILES = $(LIBSNDFILE_LICENSE_FILES)
LIBSNDFILE_WITH_LAME_AND_MPG123_CPE_ID_VALID = $(LIBSNDFILE_CPE_ID_VALID)
LIBSNDFILE_WITH_LAME_AND_MPG123_DEPENDENCIES = $(LIBSNDFILE_DEPENDENCIES) 

LIBSNDFILE_WITH_LAME_AND_MPG123_CONF_ENV = $(LIBSNDFILE_CONF_ENV)
LIBSNDFILE_WITH_LAME_AND_MPG123_CONF_OPTS = $(LIBSNDFILE_CONF_OPTS)

LIBSNDFILE_WITH_LAME_AND_MPG123_DEPENDENCIES += lame mpg123

$(eval $(autotools-package))
